#use_frameworks!

target 'QNDataManager_Example' do
  pod 'QNDataManager', :path => '../'
  pod 'Objective-LevelDB'
  pod 'YYModel'
  pod 'YTKKeyValueStore'

  target 'QNDataManager_Tests' do
    inherit! :search_paths

    
  end
end
